-- Databricks notebook source
-- DBTITLE 1,Database Creation
create database if not exists GREENHEALTH_SOURCEDATA

-- COMMAND ----------

DESCRIBE DATABASE GREENHEALTH_SOURCEDATA

-- COMMAND ----------

USE GREENHEALTH_SOURCEDATA

-- COMMAND ----------

-- DBTITLE 1,landing table - Conditions
CREATE TABLE IF NOT EXISTS CONDITIONS_LAND (
CONDITION_ID STRING,
NAME STRING,
SEVERITY_FACTOR STRING
) USING CSV
LOCATION '/mnt/SourceDataFiles/GreenHealth/Conditions.txt'

-- COMMAND ----------

DESCRIBE TABLE CONDITIONS_LAND

-- COMMAND ----------

SELECT * FROM CONDITIONS_LAND

-- COMMAND ----------

-- DBTITLE 1,Staging table - Conditions
CREATE TABLE IF NOT EXISTS GREENHEALTH_SOURCEDATA.CONDITIONS(
CONDITION_ID STRING,
NAME STRING,
SEVERITY_FACTOR FLOAT,
LOAD_DATETIME TIMESTAMP
)
USING PARQUET
PARTITIONED BY (LOAD_DATETIME)
OPTIONS(HEADER = 'FALSE', NULLVALUE = 'NA', TIMESTAMPFORMAT="YYYY-MM-DD'T'HH:MM:SS")

-- COMMAND ----------

DESCRIBE TABLE EXTENDED CONDITIONS

-- COMMAND ----------

INSERT INTO CONDITIONS SELECT CONDITION_ID, NAME, SEVERITY_FACTOR, CURRENT_TIMESTAMP() FROM CONDITIONS_LAND

-- COMMAND ----------

SELECT * FROM CONDITIONS;

-- COMMAND ----------

-- DBTITLE 1,Drop land Table - Conditions
DROP TABLE CONDITIONS_LAND

-- COMMAND ----------

SELECT * FROM CONDITIONS

-- COMMAND ----------

-- DBTITLE 1,landing table - Claims
CREATE TABLE IF NOT EXISTS CLAIMS_LAND (
ClaimID	STRING, 
MemberID STRING,	
PlanID STRING,	
Type STRING,	
ConditionID STRING,	
HospitalID STRING,	
StartDate	STRING, 
EndDate STRING,	
TotalBill STRING
) USING CSV
LOCATION '/mnt/SourceDataFiles/GreenHealth/Claims.txt'

-- COMMAND ----------

SELECT * FROM CLAIMS_LAND

-- COMMAND ----------

-- DBTITLE 1,Staging Table - Claims
CREATE TABLE IF NOT EXISTS CLAIMS(
CLAIM_ID	INT, 
MEMBER_ID INT,	
PLAN_ID STRING,	Type STRING,	
CONDITION_ID STRING,	
HOSPITAL_ID INT,	
START_DATE	STRING, 
END_DATE TIMESTAMP,	
TOTAL_BILL FLOAT,
LOAD_DATETIME TIMESTAMP
) USING PARQUET
PARTITIONED BY (LOAD_DATETIME)
OPTIONS(HEADER = 'FALSE', NULLVALUE = 'NA', TIMESTAMPFORMAT="YYYY-MM-DD'T'HH:MM:SS")

-- COMMAND ----------

INSERT INTO CLAIMS SELECT CLAIMID, MEMBERID, PLANID,TYPE, CONDITIONID,HOSPITALID, STARTDATE,ENDDATE, TOTALBILL, CURRENT_TIMESTAMP() FROM CLAIMS_LAND

-- COMMAND ----------

SELECT * FROM CLAIMS

-- COMMAND ----------

-- DBTITLE 1,Drop land Table - Claims
DROP TABLE CLAIMS_LAND

-- COMMAND ----------

-- DBTITLE 1,landing table - Doctors
CREATE TABLE IF NOT EXISTS DOCTORS_LAND (
Doctor_ID	STRING, Fname	STRING, Lname	STRING, Type	STRING, Address	STRING, City	STRING, State	STRING, PhoneNumber STRING
) USING CSV
LOCATION '/mnt/SourceDataFiles/GreenHealth/DOCTOR.txt'

-- COMMAND ----------

-- DBTITLE 1,Staging Table - Doctors
CREATE TABLE IF NOT EXISTS DOCTORS (
Doctor_ID	INT, Fname	STRING, Lname	STRING, Type	STRING, Address	STRING, City	STRING, State	STRING, PhoneNumber STRING,
LOAD_DATETIME TIMESTAMP
) USING PARQUET
PARTITIONED BY (LOAD_DATETIME)
OPTIONS(HEADER = 'FALSE', NULLVALUE = 'NA', TIMESTAMPFORMAT="YYYY-MM-DD'T'HH:MM:SS")

-- COMMAND ----------

INSERT INTO DOCTORS SELECT DOCTOR_ID, FNAME, LNAME, TYPE, ADDRESS,CITY, STATE, PHONENUMBER, CURRENT_TIMESTAMP() FROM DOCTORS_LAND

-- COMMAND ----------

SELECT * FROM DOCTORS

-- COMMAND ----------

-- DBTITLE 1,Drop land Table - Doctors
DROP TABLE DOCTORS_LAND 

-- COMMAND ----------

-- DBTITLE 1,landing table - Health Institutions
CREATE TABLE IF NOT EXISTS Health_Institution_LAND (
Hospital_ID STRING,	Name STRING,	Address	 STRING,City  STRING,	State STRING, 	ZipCode	STRING, Type STRING,	PhoneNumber	STRING, NHI STRING
) USING CSV
OPTIONS ("header" "true")
LOCATION '/mnt/SourceDataFiles/GreenHealth/Formated_Data/part-00000-tid-2958112244037192045-6b6b126f-34d0-49f3-982f-e5b9a015bba4-81-1-c000.csv'

-- COMMAND ----------

select * from Health_Institution_Land

-- COMMAND ----------

-- DBTITLE 1,Staging Table - Health Institution
CREATE TABLE IF NOT EXISTS Health_Institution (
Hospital_ID INT,	Name STRING,	Address	 STRING,City  STRING,	State STRING, 	ZipCode	STRING, Type STRING,	PhoneNumber	STRING, NHI INT, LOAD_DATETIME TIMESTAMP
) USING PARQUET
PARTITIONED BY (LOAD_DATETIME)
OPTIONS(HEADER = 'FALSE', NULLVALUE = 'NA', TIMESTAMPFORMAT="YYYY-MM-DD'T'HH:MM:SS")

-- COMMAND ----------

INSERT INTO HEALTH_INSTITUTION SELECT HOSPITAL_ID, NAME, ADDRESS,CITY, STATE, ZIPCODE, TYPE, PHONENUMBER, NHI, CURRENT_TIMESTAMP() FROM Health_Institution_Land

-- COMMAND ----------

SELECT * FROM HEALTH_INSTITUTION

-- COMMAND ----------

-- DBTITLE 1,Drop Landing Table - Health Institution
drop table Health_Institution_LAND

-- COMMAND ----------

-- DBTITLE 1,landing table - Member
CREATE TABLE IF NOT EXISTS MEMBER_LAND (
Member_ID	STRING, Fname	STRING, Lname	STRING, Address	STRING, City  STRING,	State	STRING, PhoneNumber  STRING,	PlanID STRING, 	
DOB	STRING, StartDate STRING,	EndDate STRING
) USING CSV
OPTIONS ("header" "true")
LOCATION '/mnt/SourceDataFiles/GreenHealth/Formated_Data_Member/part-00000-tid-7848495708641441021-fc7b3180-64ae-4d8d-9fe1-027ce0d64cf4-113-1-c000.csv'

-- COMMAND ----------

select * from MEMBER_LAND

-- COMMAND ----------

Drop table Member

-- COMMAND ----------

-- DBTITLE 1,Staging Table - Member
CREATE TABLE IF NOT EXISTS MEMBER (
Member_ID	STRING, Fname	STRING, Lname	STRING, Address	STRING, City  STRING,	State	STRING, PhoneNumber  STRING,	Plan_ID STRING, 	
DOB	STRING, Start_Date STRING,	End_Date STRING, LOAD_DATETIME TIMESTAMP
) USING PARQUET
PARTITIONED BY (LOAD_DATETIME)
OPTIONS(HEADER = 'FALSE', NULLVALUE = 'NA', TIMESTAMPFORMAT="YYYY-MM-DD'T'HH:MM:SS")

-- COMMAND ----------

INSERT INTO MEMBER SELECT Member_ID, FNAME, LNAME, ADDRESS,CITY, STATE, PHONENUMBER,PlanID,DOB,StartDate, ENDDATE, CURRENT_TIMESTAMP() FROM Member_Land

-- COMMAND ----------

select * from MEMBER

-- COMMAND ----------

-- DBTITLE 1,Drop Landing Table - Member
Drop table MEMBER_LAND

-- COMMAND ----------

-- DBTITLE 1,landing table - Insurance Plan
CREATE TABLE IF NOT EXISTS INSURANCE_PLAN_LAND (
Plan_ID	STRING, Name	STRING, CoPay_General STRING,	CoPay_Specialty STRING,	CoInsurance	 STRING, Deductible	 STRING, Pharmacy  STRING
) USING CSV
LOCATION '/mnt/SourceDataFiles/GreenHealth/InsurancePlan.txt'

-- COMMAND ----------

select * from INSURANCE_PLAN_LAND

-- COMMAND ----------

-- DBTITLE 1,Staging Table - Insurance Plan
CREATE TABLE IF NOT EXISTS INSURANCE_PLAN (
Plan_ID	STRING, Name	STRING, CoPay_General FLOAT,	CoPay_Specialty FLOAT,	CoInsurance	 FLOAT, Deductible	 FLOAT, Pharmacy  FLOAT, LOAD_DATETIME TIMESTAMP
)USING PARQUET
PARTITIONED BY (LOAD_DATETIME)
OPTIONS(HEADER = 'FALSE', NULLVALUE = 'NA', TIMESTAMPFORMAT="YYYY-MM-DD'T'HH:MM:SS")

-- COMMAND ----------

INSERT INTO INSURANCE_PLAN SELECT Plan_ID, NAME, CoPay_General, CoPay_Specialty,CoInsurance,Deductible, Pharmacy, CURRENT_TIMESTAMP() FROM INSURANCE_PLAN_LAND


-- COMMAND ----------

SELECT * from INSURANCE_PLAN

-- COMMAND ----------

-- DBTITLE 1,Drop Landing Table - Insurance Plan
Drop table INSURANCE_PLAN_LAND
